import Link from 'next/link'
import { ArrowRight, CalendarDays, Check, MapPin, Send } from 'lucide-react'
import { destinations, offers, whatsapp } from '@/lib/data'
import { PageShell } from '@/components/site'
export function generateStaticParams(){return destinations.map(d=>({slug:d.slug}))}
export default async function Destination({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const d=destinations.find(x=>x.slug===slug);if(!d)return <PageShell><section className="section"><div className="container"><h1>Destination introuvable</h1><Link className="btn btn-primary" href="/destinations">Retour</Link></div></section></PageShell>}
 const related=offers.filter(o=>o.destination.toLowerCase().includes(d.name.toLowerCase())||o.country.toLowerCase()===d.country.toLowerCase()).slice(0,4)
 return <PageShell><main>
  <section className="destination-detail-hero"><div className="destination-detail-image" style={{backgroundImage:`url(${d.image})`}}/><div className="detail-hero-overlay"/><div className="container destination-detail-copy"><span className="eyebrow">{d.country} · {d.type}</span><h1>{d.name}</h1><p>{d.description}</p><div className="destination-detail-actions"><Link className="btn btn-light" href={`/demande?destination=${encodeURIComponent(d.name)}`}>Créer mon voyage <ArrowRight size={16}/></Link><a className="btn btn-outline" href={whatsapp(`Bonjour Eternel Voyages, je souhaite préparer un voyage à ${d.name}.`)}><Send size={16}/> WhatsApp</a></div></div></section>
  <section className="section"><div className="container"><div className="destination-facts"><div><CalendarDays size={18}/><span><small>Meilleure période</small><b>{d.bestTime}</b></span></div><div><MapPin size={18}/><span><small>Pays</small><b>{d.country}</b></span></div><div><Check size={18}/><span><small>Organisation</small><b>Sur mesure</b></span></div></div>
   <div className="destination-intro"><div><span className="eyebrow">DÉCOUVRIR {d.name.toUpperCase()}</span><h2>Une destination, plusieurs façons de la vivre.</h2></div><p>Choisissez une idée ci-dessous ou demandez un programme personnalisé. Les tarifs et disponibilités sont confirmés par l’agence selon vos dates, voyageurs et prestations.</p></div>
   <div className="activity-pills">{d.activities.map(a=><span key={a}><Check size={14}/>{a}</span>)}</div>
   {d.gallery.length>0&&<div className="destination-gallery">{d.gallery.slice(0,4).map((g,i)=><div key={`${g.src}-${i}`} className={i===0?'gallery-large':'gallery-small'} style={{backgroundImage:`url(${g.src})`}} role="img" aria-label={g.alt}/>)}</div>}
   <div className="destination-offers"><div className="section-heading-row"><div className="section-title"><span className="eyebrow">VOYAGES ASSOCIÉS</span><h2>Inspirations pour {d.name}.</h2></div><Link className="view-all" href="/voyages">Tous les voyages <ArrowRight size={15}/></Link></div><div className="travel-grid">{related.map(o=><article className="travel-card" key={o.slug}><Link href={`/voyages/${o.slug}`} className="travel-image-link"><div className="travel-image"><div className="visual" style={{backgroundImage:`url(${o.image})`}}/><span className="travel-tag">{o.category}</span></div></Link><div className="travel-body"><div className="travel-meta"><span>{o.destination}</span><span>{o.duration||'Sur mesure'}</span></div><h3>{o.title}</h3><p>{o.description}</p><div className="travel-bottom"><span className="travel-price">{o.price||'Prix sur demande'}</span><Link className="text-link" href={`/voyages/${o.slug}`}>Découvrir <ArrowRight size={14}/></Link></div></div></article>)}</div></div>
   <div className="destination-cta"><div><span className="eyebrow">PAS ENCORE DÉCIDÉ ?</span><h2>Parlez-nous de ce que vous cherchez.</h2><p>Nous pouvons vous aider à préciser la destination, le programme et les prestations.</p></div><Link className="btn btn-primary" href={`/demande?destination=${encodeURIComponent(d.name)}`}>Demander un programme <ArrowRight size={16}/></Link></div>
  </div></section>
 </main></PageShell>}
