'use client'
import { useState } from 'react'
import { ArrowRight, CalendarDays, CheckCircle2, Hotel, Plane, Send, Users } from 'lucide-react'
import { useSearchParams } from 'next/navigation'
import { PageShell } from '@/components/site'
import { whatsapp } from '@/lib/data'

export default function Demande(){
  const params=useSearchParams(); const initialDestination=params.get('destination')||''; const [sent,setSent]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget).entries());try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,leadType:'TRAVEL_REQUEST'})});if(!r.ok)throw new Error('request');setSent(true)}catch{setError('Votre demande n’a pas pu être envoyée. Vous pouvez nous contacter directement sur WhatsApp.')}finally{setLoading(false)}}
  return <PageShell><main>
    <section className="page-hero page-hero-form"><div className="container"><span className="eyebrow">VOTRE PROJET DE VOYAGE</span><h1>Parlez-nous de la<br/><em>voyage que vous imaginez.</em></h1><p>Quelques informations suffisent pour commencer. Le budget est optionnel et aucun tarif n’est inventé lorsque les données ne sont pas confirmées.</p></div></section>
    <section className="section"><div className="container request-layout">
      <div className="form-card request-card">{sent?<div className="success-state"><CheckCircle2 size={54}/><span className="eyebrow">DEMANDE REÇUE</span><h2>Nous avons bien reçu votre demande.</h2><p>Notre équipe Eternel Voyages vous contactera prochainement pour préciser votre projet.</p><a className="btn btn-primary" href={whatsapp('Bonjour Eternel Voyages, je viens d’envoyer une demande de voyage sur votre site et je souhaite poursuivre l’échange sur WhatsApp.')}>Continuer sur WhatsApp <Send size={16}/></a></div>:<form onSubmit={submit}>
        <div className="form-section-head"><span>01</span><div><b>Votre projet</b><small>Où, quand et comment souhaitez-vous voyager ?</small></div></div>
        <div className="form-grid"><div className="form-field"><label>Destination</label><input name="destination" defaultValue={initialDestination} placeholder="Ex. Turquie, Paris, Sahara..."/></div><div className="form-field"><label>Type de voyage</label><select name="type"><option>Séjour</option><option>Circuit</option><option>Voyage sur mesure</option><option>Vol</option><option>Hôtel</option><option>Activité</option></select></div><div className="form-field"><label>Date de départ</label><div className="input-icon"><CalendarDays size={16}/><input name="departureDate" type="date"/></div></div><div className="form-field"><label>Date de retour</label><div className="input-icon"><CalendarDays size={16}/><input name="returnDate" type="date"/></div></div><div className="form-field"><label>Adultes</label><div className="input-icon"><Users size={16}/><input name="adults" type="number" min="1" defaultValue="2"/></div></div><div className="form-field"><label>Enfants</label><input name="children" type="number" min="0" defaultValue="0"/></div></div>
        <div className="form-section-head form-section-gap"><span>02</span><div><b>Préférences</b><small>Ces informations restent indicatives.</small></div></div>
        <div className="form-grid"><div className="form-field"><label>Budget indicatif <span>(optionnel)</span></label><input name="budget" placeholder="Ex. 150 000 DA / personne"/></div><div className="form-field"><label>Hôtel souhaité</label><div className="input-icon"><Hotel size={16}/><input name="hotel" placeholder="Catégorie ou préférence"/></div></div><div className="form-field"><label>Vol souhaité</label><div className="input-icon"><Plane size={16}/><input name="flight" placeholder="Direct, classe, horaires..."/></div></div><div className="form-field full"><label>Message</label><textarea name="message" rows={5} placeholder="Parlez-nous de vos envies, contraintes ou activités souhaitées..."/></div></div>
        <div className="form-section-head form-section-gap"><span>03</span><div><b>Vos coordonnées</b><small>Pour que l’agence puisse vous répondre.</small></div></div>
        <div className="form-grid"><div className="form-field"><label>Nom *</label><input name="name" required/></div><div className="form-field"><label>Téléphone *</label><input name="phone" required/></div><div className="form-field"><label>Email</label><input name="email" type="email"/></div><div className="form-field"><label>WhatsApp</label><input name="whatsapp" placeholder="Si différent du téléphone"/></div></div>
        {error&&<p className="form-error">{error}</p>}<button className="btn btn-primary form-submit" disabled={loading}>{loading?'Envoi en cours...':'Recevoir mon programme'} <ArrowRight size={16}/></button><p className="form-disclaimer">Les informations servent à préparer votre demande. Les disponibilités, prestations et tarifs sont confirmés par l’agence.</p>
      </form>}</div>
      <aside className="request-aside"><span className="eyebrow">COMMENT ÇA MARCHE ?</span><h2>Une demande, puis un échange humain.</h2><div className="aside-steps"><div><b>01</b><span><strong>Vous décrivez</strong><small>Votre destination, vos dates et vos envies.</small></span></div><div><b>02</b><span><strong>Nous étudions</strong><small>Les options disponibles pour votre projet.</small></span></div><div><b>03</b><span><strong>Vous recevez</strong><small>Une proposition claire à confirmer ensemble.</small></span></div></div><div className="aside-note">Le budget est <strong>facultatif</strong>. Vous pouvez simplement nous expliquer le voyage que vous imaginez.</div></aside>
    </div></section>
  </main></PageShell>
}
