'use client'
import Link from 'next/link'
import { ArrowRight, Heart, MapPin, Search, SlidersHorizontal } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { Offer } from '@/lib/data'

export function TravelCatalog({offers}:{offers:Offer[]}){
 const [query,setQuery]=useState(''); const [country,setCountry]=useState('all'); const [type,setType]=useState('all')
 const results=useMemo(()=>offers.filter(o=>{const q=query.toLowerCase().trim();return (!q||`${o.title} ${o.destination} ${o.country}`.toLowerCase().includes(q))&&(country==='all'||o.country===country)&&(type==='all'||o.category===type)}),[offers,query,country,type])
 return <div><div className="catalog-toolbar"><div className="catalog-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une destination, un voyage..."/></div><div className="catalog-filters"><label><span>Pays</span><select value={country} onChange={e=>setCountry(e.target.value)}><option value="all">Tous</option>{Array.from(new Set(offers.map(o=>o.country))).map(x=><option key={x}>{x}</option>)}</select></label><label><span>Type</span><select value={type} onChange={e=>setType(e.target.value)}><option value="all">Tous les types</option>{Array.from(new Set(offers.map(o=>o.category))).map(x=><option key={x}>{x}</option>)}</select></label></div></div><div className="catalog-result-head"><span><b>{results.length}</b> inspiration{results.length!==1?'s':''}</span><span><SlidersHorizontal size={14}/> Disponibilité à confirmer</span></div>{results.length===0?<div className="empty-state"><Search size={28}/><h3>Aucun voyage trouvé</h3><p>Essayez une autre destination ou demandez un voyage sur mesure.</p><Link className="btn btn-primary" href="/demande">Créer mon voyage <ArrowRight size={15}/></Link></div>:<div className="cards travel-grid">{results.map(o=><article className="travel-card" key={o.slug}><Link href={`/voyages/${o.slug}`} className="travel-image-link"><div className="travel-image"><div className="visual" style={{backgroundImage:`url(${o.image})`}}/><span className="travel-tag">{o.category}</span></div></Link><div className="travel-body"><div className="travel-meta"><span><MapPin size={12}/>{o.destination}</span><span>{o.duration||'Sur mesure'}</span></div><h3>{o.title}</h3><p>{o.description}</p><div className="travel-bottom"><span className="travel-price">{o.price||'Prix sur demande'}</span><Link className="text-link" href={`/voyages/${o.slug}`}>Détails <ArrowRight size={14}/></Link></div></div></article>)}</div>}</div>
}
