import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, Clock3, Heart, MapPin, Phone, Send, Share2, X } from 'lucide-react'
import { offers, phone, whatsapp } from '@/lib/data'
import { PageShell } from '@/components/site'
export function generateStaticParams(){return offers.map(o=>({slug:o.slug}))}
export default async function OfferPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const o=offers.find(x=>x.slug===slug);if(!o)return <PageShell><section className="section"><div className="container"><h1>Voyage introuvable</h1><Link className="btn btn-primary" href="/voyages">Retour aux voyages</Link></div></section></PageShell>
 const msg=`Bonjour Eternel Voyages, je suis intéressé(e) par ${o.title}. Je souhaite recevoir le programme, les disponibilités et le tarif.`
 return <PageShell><main>
  <section className="detail-hero"><div className="detail-hero-bg" style={{backgroundImage:`url(${o.image})`}}/><div className="detail-hero-overlay"/><div className="container detail-hero-inner"><Link className="back-link" href="/voyages"><ArrowLeft size={15}/> Tous les voyages</Link><div className="detail-copy"><span className="eyebrow">{o.category} · {o.country}</span><h1>{o.title}</h1><p>{o.description}</p><div className="detail-meta"><span><MapPin size={15}/>{o.destination}</span><span><Clock3 size={15}/>{o.duration||'Durée à confirmer'}</span><span>{o.type||o.category}</span></div><div className="detail-price">{o.price ? <><small>À partir de</small>{o.price} <small>/ personne</small></> : <><small>Tarification</small>Prix sur demande</>}</div><div className="action-row"><a className="btn btn-light" href={whatsapp(msg)}><Send size={16}/> Demander un devis</a><Link className="btn btn-outline" href={`/demande?destination=${encodeURIComponent(o.destination)}&offer=${encodeURIComponent(o.title)}`}>Recevoir le programme <ArrowRight size={16}/></Link></div></div></div></section>
  <section className="section detail-content"><div className="container detail-content-grid"><div className="detail-main">
    {o.gallery&&o.gallery.length>1&&<div className="detail-gallery">{o.gallery.map((g,i)=><div key={`${g.src}-${i}`} className={i===0?'gallery-large':'gallery-small'} style={{backgroundImage:`url(${g.src})`}} role="img" aria-label={g.alt}/>)}</div>}
    <div className="detail-section"><span className="eyebrow">À PROPOS DU VOYAGE</span><h2>Une expérience à construire selon votre projet.</h2><p>{o.description} Les éléments affichés comme indicatifs ne constituent pas une disponibilité ou un tarif confirmé.</p></div>
    {o.itinerary&&<div className="detail-section"><span className="eyebrow">PROGRAMME INDICATIF</span><h2>Itinéraire</h2><div className="itinerary">{o.itinerary.map(day=><div className="itinerary-row" key={day.day}><b>{day.day}</b><div><h3>{day.title}</h3><p>{day.description}</p></div></div>)}</div></div>}
    <div className="detail-columns"><div className="detail-section compact-detail"><span className="eyebrow">INCLUS</span><h3>Ce qui peut être inclus</h3><ul>{(o.included||['Prestations à confirmer selon le programme']).map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></div><div className="detail-section compact-detail"><span className="eyebrow">NON INCLUS</span><h3>À prévoir</h3><ul>{(o.excluded||['Éléments non prévus dans le programme confirmé']).map(x=><li key={x}><X size={16}/>{x}</li>)}</ul></div></div>
    <div className="detail-section info-panel"><span className="eyebrow">INFORMATIONS IMPORTANTES</span><h3>Disponibilité et tarif</h3><p>Les dates, hôtels, vols, disponibilités et tarifs dépendent du programme, de la saison et des conditions au moment de la demande. Lorsque le prix n’est pas confirmé, le site affiche <strong>Prix sur demande</strong>.</p></div>
  </div><aside className="detail-sidebar"><div className="sticky-card"><span className="eyebrow">VOTRE PROJET</span><h3>Vous souhaitez partir ?</h3><p>Demandez les disponibilités et recevez une proposition adaptée à vos dates et voyageurs.</p><Link className="btn btn-primary full-btn" href={`/demande?destination=${encodeURIComponent(o.destination)}&offer=${encodeURIComponent(o.title)}`}>Demander un devis <ArrowRight size={16}/></Link><a className="sidebar-link" href={whatsapp(msg)}><Send size={15}/> WhatsApp</a><a className="sidebar-link" href={`tel:${phone}`}><Phone size={15}/> Appeler l’agence</a><div className="sidebar-actions"><button aria-label="Ajouter aux favoris"><Heart size={17}/> Favoris</button><button aria-label="Partager"><Share2 size={17}/> Partager</button></div></div></aside></div></section>
 </main></PageShell>}
